const curiosidadesDesenho = [
  "Antes de existirem cadernos, as pessoas já pintavam nas cavernas, como nas pinturas de Caverna de Altamira, usando terra e carvão. 🎨",
  "Leonardo da Vinci desenhava máquinas voadoras séculos antes de o avião existir. ✈️",
  "Vincent van Gogh gostava de pintar com cores fortes para mostrar sentimentos. Pintou céus cheios de estrelas e girassóis brilhantes. 🌌",
  "Michelangelo esculpiu e pintou obras gigantes. Acreditava que as figuras já estavam escondidas dentro da pedra. 🗿",
  "Raffaello Sanzio pintava pessoas calmas e harmoniosas. Suas obras parecem organizadas e tranquilas. 👼",
  "Leonardo da Vinci amava desenhar, pintar e inventar. Observava tudo com muita curiosidade. 🔍",
  "Romero Britto usa muitas cores alegres e formas simples. Suas obras parecem festas desenhadas. 🎈",
  "Djanira da Motta e Silva pintava o dia a dia das pessoas, o trabalho e as tradições do Brasil. 🇧🇷",
  "Frida Kahlo pintava a si mesma para contar sua história. Mostrava sentimentos com coragem. 🌺",
  "Salvador Dalí criava imagens que parecem sonhos estranhos e divertidos. ⏰",
  "Caravaggio gostava de contrastes fortes entre luz e sombra para contar histórias. 🔦",
  "Tarsila do Amaral pintou o Brasil com cores vivas e formas diferentes, inspiradas na imaginação. 🎨",
  "Ivan Cruz retratava crianças brincando de amarelinha, pipa e roda. 🪁",
  "Candido Portinari mostrou em suas pinturas a vida das pessoas simples e trabalhadoras. 👨‍🌾",
  "Henri Matisse amava cores alegres e recortes de papel que viravam arte. ✂️",
  "René Magritte gostava de fazer a gente pensar: será que tudo é o que parece? 🧐",
  "Claude Monet pintava a natureza observando a luz do sol em diferentes momentos. ☀️",
  "Georges Seurat criava imagens usando muitos pontinhos coloridos. 🔵",
  "Edgar Degas adorava desenhar bailarinas em movimento. 🩰",
  "Edvard Munch usava a pintura para mostrar emoções fortes. 😱",
  "Rembrandt pintava rostos cheios de expressão e emoção. 🎭",
  "Hélio Oiticica criava obras para as pessoas entrarem, tocarem e participarem. 🕺",
  "Di Cavalcanti mostrava festas, músicas e pessoas do Brasil. 🎉",
  "José Ferraz de Almeida Júnior pintava a vida no interior, com cenas simples do cotidiano. 🌾",
  "Georgina de Albuquerque retratava cenas históricas e momentos importantes do Brasil. 📜",
  "Pedro Américo criou grandes pinturas que contam a história do país. ⚔️",
  "Lasar Segall falava sobre sentimentos, viagens e desafios das pessoas. 🌍",
  "Alfredo Volpi ficou famoso por pintar bandeirinhas coloridas. 🏠",
  "Beatriz Milhazes mistura cores, flores e formas inspiradas na cultura brasileira. 🌼"
];
